// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openrtb-ydext-dsp.proto

package com.google.openrtb.youdao;

public final class OpenRtbYDExtForDsp {
  private OpenRtbYDExtForDsp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.google.openrtb.youdao.OpenRtbYDExtForDsp.sasset);
    registry.add(com.google.openrtb.youdao.OpenRtbYDExtForDsp.dataAssetType);
    registry.add(com.google.openrtb.youdao.OpenRtbYDExtForDsp.ssid);
    registry.add(com.google.openrtb.youdao.OpenRtbYDExtForDsp.battri);
    registry.add(com.google.openrtb.youdao.OpenRtbYDExtForDsp.tfc);
    registry.add(com.google.openrtb.youdao.OpenRtbYDExtForDsp.did);
    registry.add(com.google.openrtb.youdao.OpenRtbYDExtForDsp.dpid);
    registry.add(com.google.openrtb.youdao.OpenRtbYDExtForDsp.attri);
  }
  public static final int SASSET_FIELD_NUMBER = 100;
  /**
   * <code>extend .com.google.openrtb.NativeRequest.Asset { ... }</code>
   *
   * <pre>
   **
   * Standard asset.
   * </pre>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.NativeRequest.Asset,
      com.google.openrtb.OpenRtb.NativeRequest.Asset> sasset = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.OpenRtb.NativeRequest.Asset.class,
        com.google.openrtb.OpenRtb.NativeRequest.Asset.getDefaultInstance());
  public static final int DATAASSETTYPE_FIELD_NUMBER = 100;
  /**
   * <code>extend .com.google.openrtb.NativeRequest.Asset.Data { ... }</code>
   *
   * <pre>
   **
   * google openrtb NativeRequest.Asset.Data.type is enum, could not extended easily.
   * using int dataAssetType instead.
   * DSP will ignore NativeRequest.Asset.Data.type even request has to set it.
   * </pre>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.NativeRequest.Asset.Data,
      java.lang.Integer> dataAssetType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int SSID_FIELD_NUMBER = 100;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Imp { ... }</code>
   *
   * <pre>
   **
   * Standard schema ID.
   * </pre>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Imp,
      java.lang.Integer> ssid = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int BATTRI_FIELD_NUMBER = 100;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Imp.Native { ... }</code>
   *
   * <pre>
   **
   * google openrtb BidRequest.Imp.Native.battr is enum, could not extended easily.
   * using battri to identify another battr
   * </pre>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Imp.Native,
      java.util.List<java.lang.Integer>> battri = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int TFC_FIELD_NUMBER = 100;
  /**
   * <code>extend .com.google.openrtb.BidRequest { ... }</code>
   *
   * <pre>
   **
   * trackFromClient标识对于本次竞价请求的获胜者，是否将从客户端发送tracker
   * </pre>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest,
      java.lang.Boolean> tfc = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int DID_FIELD_NUMBER = 100;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Device { ... }</code>
   *
   * <pre>
   **
   * Hardware device ID (e.g., IMEI), in the clear (i.e., not hashed).
   * </pre>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Device,
      java.lang.String> did = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int DPID_FIELD_NUMBER = 101;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Device { ... }</code>
   *
   * <pre>
   **
   * Platform device ID (e.g., Android ID) in the clear (i.e., not hashed).
   * </pre>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Device,
      java.lang.String> dpid = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int ATTRI_FIELD_NUMBER = 100;
  /**
   * <code>extend .com.google.openrtb.BidResponse.SeatBid.Bid { ... }</code>
   *
   * <pre>
   **
   * google openrtb BidResponse.SeatBid.Bid.attri is enum, could not extended easily.
   * using attri to identify another attri
   * </pre>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidResponse.SeatBid.Bid,
      java.util.List<java.lang.Integer>> attri = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027openrtb-ydext-dsp.proto\022\031com.google.op" +
      "enrtb.youdao\032\ropenrtb.proto:`\n\006sasset\022\'." +
      "com.google.openrtb.NativeRequest.Asset\030d" +
      " \001(\0132\'.com.google.openrtb.NativeRequest." +
      "Asset:C\n\rdataAssetType\022,.com.google.open" +
      "rtb.NativeRequest.Asset.Data\030d \001(\005:0\n\004ss" +
      "id\022\".com.google.openrtb.BidRequest.Imp\030d" +
      " \001(\005:=\n\006battri\022).com.google.openrtb.BidR" +
      "equest.Imp.Native\030d \003(\005B\002\020\001:2\n\003tfc\022\036.com" +
      ".google.openrtb.BidRequest\030d \001(\010:\005false:",
      "2\n\003did\022%.com.google.openrtb.BidRequest.D" +
      "evice\030d \001(\t:3\n\004dpid\022%.com.google.openrtb" +
      ".BidRequest.Device\030e \001(\t:>\n\005attri\022+.com." +
      "google.openrtb.BidResponse.SeatBid.Bid\030d" +
      " \003(\005B\002\020\001B\024B\022OpenRtbYDExtForDsp"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.openrtb.OpenRtb.getDescriptor(),
        }, assigner);
    sasset.internalInit(descriptor.getExtensions().get(0));
    dataAssetType.internalInit(descriptor.getExtensions().get(1));
    ssid.internalInit(descriptor.getExtensions().get(2));
    battri.internalInit(descriptor.getExtensions().get(3));
    tfc.internalInit(descriptor.getExtensions().get(4));
    did.internalInit(descriptor.getExtensions().get(5));
    dpid.internalInit(descriptor.getExtensions().get(6));
    attri.internalInit(descriptor.getExtensions().get(7));
    com.google.openrtb.OpenRtb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
